# Generated by Django 5.1.6 on 2025-02-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='how_to_cook',
            field=models.TextField(default='nothing'),
        ),
    ]
